version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port dla komunikacji z aplikacjami
      - "15672:15672" # Port dla panelu zarządzania
    environment:
      RABBITMQ_DEFAULT_USER: user # Domyślny użytkownik
      RABBITMQ_DEFAULT_PASS: password # Domyślne hasło
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs: